//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileClaims.iOS {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizableBrand {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableBrand() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MobileClaims.iOS.LocalizableBrand", typeof(LocalizableBrand).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string GSC {
            get {
                return ResourceManager.GetString("GSC", resourceCulture);
            }
        }
        
        public static string GreenShield {
            get {
                return ResourceManager.GetString("GreenShield", resourceCulture);
            }
        }
        
        public static string GreenShieldCanada {
            get {
                return ResourceManager.GetString("GreenShieldCanada", resourceCulture);
            }
        }
        
        public static string WalletPKPassDescription {
            get {
                return ResourceManager.GetString("WalletPKPassDescription", resourceCulture);
            }
        }
        
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        public static string PhoneNumberFPPM {
            get {
                return ResourceManager.GetString("PhoneNumberFPPM", resourceCulture);
            }
        }
        
        public static string EligibilityResultsNote {
            get {
                return ResourceManager.GetString("EligibilityResultsNote", resourceCulture);
            }
        }
        
        public static string EligibilityInquiryNote {
            get {
                return ResourceManager.GetString("EligibilityInquiryNote", resourceCulture);
            }
        }
        
        public static string UnableToDetermineEligibility {
            get {
                return ResourceManager.GetString("UnableToDetermineEligibility", resourceCulture);
            }
        }
    }
}
