//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileClaims.Core {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BrandResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BrandResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MobileClaims.Core.BrandResource", typeof(BrandResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string BrandAcronym {
            get {
                return ResourceManager.GetString("BrandAcronym", resourceCulture);
            }
        }
        
        public static string BrandShortDisplayName {
            get {
                return ResourceManager.GetString("BrandShortDisplayName", resourceCulture);
            }
        }
        
        public static string BrandFullDisplayName {
            get {
                return ResourceManager.GetString("BrandFullDisplayName", resourceCulture);
            }
        }
        
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        public static string WebInstructions {
            get {
                return ResourceManager.GetString("WebInstructions", resourceCulture);
            }
        }
        
        public static string WebInstructionsLink {
            get {
                return ResourceManager.GetString("WebInstructionsLink", resourceCulture);
            }
        }
        
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        public static string Legal {
            get {
                return ResourceManager.GetString("Legal", resourceCulture);
            }
        }
        
        public static string IAgreeToTC {
            get {
                return ResourceManager.GetString("IAgreeToTC", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsGeneral1 {
            get {
                return ResourceManager.GetString("TermsAndConditionsGeneral1", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsGeneral2 {
            get {
                return ResourceManager.GetString("TermsAndConditionsGeneral2", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsGeneral3 {
            get {
                return ResourceManager.GetString("TermsAndConditionsGeneral3", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsGeneral4 {
            get {
                return ResourceManager.GetString("TermsAndConditionsGeneral4", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsGeneral5 {
            get {
                return ResourceManager.GetString("TermsAndConditionsGeneral5", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsGeneral6 {
            get {
                return ResourceManager.GetString("TermsAndConditionsGeneral6", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsGeneral7 {
            get {
                return ResourceManager.GetString("TermsAndConditionsGeneral7", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsGeneral8 {
            get {
                return ResourceManager.GetString("TermsAndConditionsGeneral8", resourceCulture);
            }
        }
        
        public static string GeneralContent6 {
            get {
                return ResourceManager.GetString("GeneralContent6", resourceCulture);
            }
        }
        
        public static string GeneralContent8 {
            get {
                return ResourceManager.GetString("GeneralContent8", resourceCulture);
            }
        }
        
        public static string MyIdCardText {
            get {
                return ResourceManager.GetString("MyIdCardText", resourceCulture);
            }
        }
        
        public static string claimConfirm_description {
            get {
                return ResourceManager.GetString("claimConfirm_description", resourceCulture);
            }
        }
        
        public static string claimConfirm_id_number {
            get {
                return ResourceManager.GetString("claimConfirm_id_number", resourceCulture);
            }
        }
        
        public static string DisclaimerFirstParagraph {
            get {
                return ResourceManager.GetString("DisclaimerFirstParagraph", resourceCulture);
            }
        }
        
        public static string DisclaimerSecondParagraph {
            get {
                return ResourceManager.GetString("DisclaimerSecondParagraph", resourceCulture);
            }
        }
        
        public static string AuditDisclaimerFirstParagraph {
            get {
                return ResourceManager.GetString("AuditDisclaimerFirstParagraph", resourceCulture);
            }
        }
        
        public static string AuditDisclaimerSecondParagraph {
            get {
                return ResourceManager.GetString("AuditDisclaimerSecondParagraph", resourceCulture);
            }
        }
        
        public static string AuditDisclaimerThirdParagraph {
            get {
                return ResourceManager.GetString("AuditDisclaimerThirdParagraph", resourceCulture);
            }
        }
        
        public static string EverythingYouNeedToKnow {
            get {
                return ResourceManager.GetString("EverythingYouNeedToKnow", resourceCulture);
            }
        }
        
        public static string GreenShieldIDNumber {
            get {
                return ResourceManager.GetString("GreenShieldIDNumber", resourceCulture);
            }
        }
        
        public static string GreenShieldIDNumberNoColon {
            get {
                return ResourceManager.GetString("GreenShieldIDNumberNoColon", resourceCulture);
            }
        }
        
        public static string submittedToGSC {
            get {
                return ResourceManager.GetString("submittedToGSC", resourceCulture);
            }
        }
        
        public static string Find_a_health_provider_faq_url {
            get {
                return ResourceManager.GetString("Find_a_health_provider_faq_url", resourceCulture);
            }
        }
        
        public static string Understanding_pharmacy_quality_ratings_url {
            get {
                return ResourceManager.GetString("Understanding_pharmacy_quality_ratings_url", resourceCulture);
            }
        }
        
        public static string cardDescription {
            get {
                return ResourceManager.GetString("cardDescription", resourceCulture);
            }
        }
        
        public static string NoActiveClaimsLabel {
            get {
                return ResourceManager.GetString("NoActiveClaimsLabel", resourceCulture);
            }
        }
        
        public static string VisionEnhancementsMessage {
            get {
                return ResourceManager.GetString("VisionEnhancementsMessage", resourceCulture);
            }
        }
        
        public static string VisionEnhancementsProgramName {
            get {
                return ResourceManager.GetString("VisionEnhancementsProgramName", resourceCulture);
            }
        }
        
        public static string VisionEnhancementsProgramAdditionalInfo {
            get {
                return ResourceManager.GetString("VisionEnhancementsProgramAdditionalInfo", resourceCulture);
            }
        }
        
        public static string ClaimDetailsOtherBenefitsTitle {
            get {
                return ResourceManager.GetString("ClaimDetailsOtherBenefitsTitle", resourceCulture);
            }
        }
        
        public static string SupportCenterLink {
            get {
                return ResourceManager.GetString("SupportCenterLink", resourceCulture);
            }
        }
        
        public static string DirectDepositEFTAlert {
            get {
                return ResourceManager.GetString("DirectDepositEFTAlert", resourceCulture);
            }
        }
        
        public static string DirectDepositOptInMessage {
            get {
                return ResourceManager.GetString("DirectDepositOptInMessage", resourceCulture);
            }
        }
        
        public static string DDConfirmAuthoriseDepositFundLabel {
            get {
                return ResourceManager.GetString("DDConfirmAuthoriseDepositFundLabel", resourceCulture);
            }
        }
        
        public static string DDResultDisclaimer3 {
            get {
                return ResourceManager.GetString("DDResultDisclaimer3", resourceCulture);
            }
        }
    }
}
