//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileClaims.Core {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MobileClaims.Core.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ChangeForLife_MessageDialogButtonClose {
            get {
                return ResourceManager.GetString("ChangeForLife_MessageDialogButtonClose", resourceCulture);
            }
        }
        
        public static string ChangeForLife_MessageDialogTitle {
            get {
                return ResourceManager.GetString("ChangeForLife_MessageDialogTitle", resourceCulture);
            }
        }
        
        public static string ChangeForLife_MessageNoAccess {
            get {
                return ResourceManager.GetString("ChangeForLife_MessageNoAccess", resourceCulture);
            }
        }
        
        public static string HCSAPlanParticipantChangedMessage {
            get {
                return ResourceManager.GetString("HCSAPlanParticipantChangedMessage", resourceCulture);
            }
        }
        
        public static string HCSAPlanParticipantChangedMessage2 {
            get {
                return ResourceManager.GetString("HCSAPlanParticipantChangedMessage2", resourceCulture);
            }
        }
        
        public static string HCSAPlanParticipantChangedTitle {
            get {
                return ResourceManager.GetString("HCSAPlanParticipantChangedTitle", resourceCulture);
            }
        }
        
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        public static string ClaimsHistory {
            get {
                return ResourceManager.GetString("ClaimsHistory", resourceCulture);
            }
        }
        
        public static string ClaimsHistoryCaps {
            get {
                return ResourceManager.GetString("ClaimsHistoryCaps", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string noCaps {
            get {
                return ResourceManager.GetString("noCaps", resourceCulture);
            }
        }
        
        public static string RehydrationMessage {
            get {
                return ResourceManager.GetString("RehydrationMessage", resourceCulture);
            }
        }
        
        public static string NewClaim {
            get {
                return ResourceManager.GetString("NewClaim", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string yesCaps {
            get {
                return ResourceManager.GetString("yesCaps", resourceCulture);
            }
        }
        
        public static string AmountPreviouslyPaid {
            get {
                return ResourceManager.GetString("AmountPreviouslyPaid", resourceCulture);
            }
        }
        
        public static string ChooseTypeOfClaim {
            get {
                return ResourceManager.GetString("ChooseTypeOfClaim", resourceCulture);
            }
        }
        
        public static string ChooseTypeOfExpense {
            get {
                return ResourceManager.GetString("ChooseTypeOfExpense", resourceCulture);
            }
        }
        
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        public static string DateOfExpense {
            get {
                return ResourceManager.GetString("DateOfExpense", resourceCulture);
            }
        }
        
        public static string EmptyExpenseAmount {
            get {
                return ResourceManager.GetString("EmptyExpenseAmount", resourceCulture);
            }
        }
        
        public static string EmptyExpenseDate {
            get {
                return ResourceManager.GetString("EmptyExpenseDate", resourceCulture);
            }
        }
        
        public static string ExpenseAmountIsInvalid {
            get {
                return ResourceManager.GetString("ExpenseAmountIsInvalid", resourceCulture);
            }
        }
        
        public static string ExpenseIsFutureDated {
            get {
                return ResourceManager.GetString("ExpenseIsFutureDated", resourceCulture);
            }
        }
        
        public static string OtherAmountIsInvalid {
            get {
                return ResourceManager.GetString("OtherAmountIsInvalid", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string SelectThePlanParticipant {
            get {
                return ResourceManager.GetString("SelectThePlanParticipant", resourceCulture);
            }
        }
        
        public static string TotalAmountClaimed {
            get {
                return ResourceManager.GetString("TotalAmountClaimed", resourceCulture);
            }
        }
        
        public static string ExpenseTypesWithReferralRequired {
            get {
                return ResourceManager.GetString("ExpenseTypesWithReferralRequired", resourceCulture);
            }
        }
        
        public static string MoreThanFiveClaims {
            get {
                return ResourceManager.GetString("MoreThanFiveClaims", resourceCulture);
            }
        }
        
        public static string MoreThanTenClaims {
            get {
                return ResourceManager.GetString("MoreThanTenClaims", resourceCulture);
            }
        }
        
        public static string ReferralRequired {
            get {
                return ResourceManager.GetString("ReferralRequired", resourceCulture);
            }
        }
        
        public static string HCSAReferralTypes {
            get {
                return ResourceManager.GetString("HCSAReferralTypes", resourceCulture);
            }
        }
        
        public static string NoClaimDetailsEntered {
            get {
                return ResourceManager.GetString("NoClaimDetailsEntered", resourceCulture);
            }
        }
        
        public static string ClaimsHistorySearchViewModel_DisplayByDateRange {
            get {
                return ResourceManager.GetString("ClaimsHistorySearchViewModel_DisplayByDateRange", resourceCulture);
            }
        }
        
        public static string ClaimsHistorySearchViewModel_DisplayByYear {
            get {
                return ResourceManager.GetString("ClaimsHistorySearchViewModel_DisplayByYear", resourceCulture);
            }
        }
        
        public static string ClaimsHistorySearchViewModel_DisplayByYearToDate {
            get {
                return ResourceManager.GetString("ClaimsHistorySearchViewModel_DisplayByYearToDate", resourceCulture);
            }
        }
        
        public static string BasedOnServiceDateOfClaim {
            get {
                return ResourceManager.GetString("BasedOnServiceDateOfClaim", resourceCulture);
            }
        }
        
        public static string Benefit {
            get {
                return ResourceManager.GetString("Benefit", resourceCulture);
            }
        }
        
        public static string ClaimDetails {
            get {
                return ResourceManager.GetString("ClaimDetails", resourceCulture);
            }
        }
        
        public static string ClaimedAmount {
            get {
                return ResourceManager.GetString("ClaimedAmount", resourceCulture);
            }
        }
        
        public static string ClaimFormNumber {
            get {
                return ResourceManager.GetString("ClaimFormNumber", resourceCulture);
            }
        }
        
        public static string Claims {
            get {
                return ResourceManager.GetString("Claims", resourceCulture);
            }
        }
        
        public static string ClaimsFor {
            get {
                return ResourceManager.GetString("ClaimsFor", resourceCulture);
            }
        }
        
        public static string ClaimsPaidTo {
            get {
                return ResourceManager.GetString("ClaimsPaidTo", resourceCulture);
            }
        }
        
        public static string ClaimType {
            get {
                return ResourceManager.GetString("ClaimType", resourceCulture);
            }
        }
        
        public static string CopayDeductible {
            get {
                return ResourceManager.GetString("CopayDeductible", resourceCulture);
            }
        }
        
        public static string DateOfInquiry {
            get {
                return ResourceManager.GetString("DateOfInquiry", resourceCulture);
            }
        }
        
        public static string DepositDate {
            get {
                return ResourceManager.GetString("DepositDate", resourceCulture);
            }
        }
        
        public static string DirectDepositNumber {
            get {
                return ResourceManager.GetString("DirectDepositNumber", resourceCulture);
            }
        }
        
        public static string DisplayBy {
            get {
                return ResourceManager.GetString("DisplayBy", resourceCulture);
            }
        }
        
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        public static string OtherPaidAmount {
            get {
                return ResourceManager.GetString("OtherPaidAmount", resourceCulture);
            }
        }
        
        public static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        public static string PaidTo {
            get {
                return ResourceManager.GetString("PaidTo", resourceCulture);
            }
        }
        
        public static string PaymentAmount {
            get {
                return ResourceManager.GetString("PaymentAmount", resourceCulture);
            }
        }
        
        public static string PaymentCurrency {
            get {
                return ResourceManager.GetString("PaymentCurrency", resourceCulture);
            }
        }
        
        public static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        public static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        public static string PlanMember {
            get {
                return ResourceManager.GetString("PlanMember", resourceCulture);
            }
        }
        
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        public static string SearchCriteria {
            get {
                return ResourceManager.GetString("SearchCriteria", resourceCulture);
            }
        }
        
        public static string ServiceDate {
            get {
                return ResourceManager.GetString("ServiceDate", resourceCulture);
            }
        }
        
        public static string DentalServiceDate {
            get {
                return ResourceManager.GetString("DentalServiceDate", resourceCulture);
            }
        }
        
        public static string ServiceDescription {
            get {
                return ResourceManager.GetString("ServiceDescription", resourceCulture);
            }
        }
        
        public static string StatementDate {
            get {
                return ResourceManager.GetString("StatementDate", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string DateNotWithinLast12Months {
            get {
                return ResourceManager.GetString("DateNotWithinLast12Months", resourceCulture);
            }
        }
        
        public static string EndDateIsNotAValidDate {
            get {
                return ResourceManager.GetString("EndDateIsNotAValidDate", resourceCulture);
            }
        }
        
        public static string PleaseEnsureStartDatePreceedsEndDate {
            get {
                return ResourceManager.GetString("PleaseEnsureStartDatePreceedsEndDate", resourceCulture);
            }
        }
        
        public static string PleaseSelectAYear {
            get {
                return ResourceManager.GetString("PleaseSelectAYear", resourceCulture);
            }
        }
        
        public static string StartDateIsNotAValidDate {
            get {
                return ResourceManager.GetString("StartDateIsNotAValidDate", resourceCulture);
            }
        }
        
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        public static string Participant {
            get {
                return ResourceManager.GetString("Participant", resourceCulture);
            }
        }
        
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        public static string CashedDate {
            get {
                return ResourceManager.GetString("CashedDate", resourceCulture);
            }
        }
        
        public static string ChequeNumber {
            get {
                return ResourceManager.GetString("ChequeNumber", resourceCulture);
            }
        }
        
        public static string ChequeStatus {
            get {
                return ResourceManager.GetString("ChequeStatus", resourceCulture);
            }
        }
        
        public static string EOB {
            get {
                return ResourceManager.GetString("EOB", resourceCulture);
            }
        }
        
        public static string PleaseSelectBenefit {
            get {
                return ResourceManager.GetString("PleaseSelectBenefit", resourceCulture);
            }
        }
        
        public static string PleaseSelectPayee {
            get {
                return ResourceManager.GetString("PleaseSelectPayee", resourceCulture);
            }
        }
        
        public static string SearchedFor {
            get {
                return ResourceManager.GetString("SearchedFor", resourceCulture);
            }
        }
        
        public static string TotalsCaps {
            get {
                return ResourceManager.GetString("TotalsCaps", resourceCulture);
            }
        }
        
        public static string HCSAChooseClaimTypeScreenTitle {
            get {
                return ResourceManager.GetString("HCSAChooseClaimTypeScreenTitle", resourceCulture);
            }
        }
        
        public static string HCSAQuestion {
            get {
                return ResourceManager.GetString("HCSAQuestion", resourceCulture);
            }
        }
        
        public static string HCSASubtitle {
            get {
                return ResourceManager.GetString("HCSASubtitle", resourceCulture);
            }
        }
        
        public static string TermsAndConditionsTitle {
            get {
                return ResourceManager.GetString("TermsAndConditionsTitle", resourceCulture);
            }
        }
        
        public static string ExistingHCSAClaimDetailsMessage {
            get {
                return ResourceManager.GetString("ExistingHCSAClaimDetailsMessage", resourceCulture);
            }
        }
        
        public static string AwaitingPayment {
            get {
                return ResourceManager.GetString("AwaitingPayment", resourceCulture);
            }
        }
        
        public static string CannotBeSubmittedOnlineMessage {
            get {
                return ResourceManager.GetString("CannotBeSubmittedOnlineMessage", resourceCulture);
            }
        }
        
        public static string SubmitClaim {
            get {
                return ResourceManager.GetString("SubmitClaim", resourceCulture);
            }
        }
        
        public static string claimConfirm_detais {
            get {
                return ResourceManager.GetString("claimConfirm_detais", resourceCulture);
            }
        }
        
        public static string claimConfirm_government {
            get {
                return ResourceManager.GetString("claimConfirm_government", resourceCulture);
            }
        }
        
        public static string claimConfirm_participant {
            get {
                return ResourceManager.GetString("claimConfirm_participant", resourceCulture);
            }
        }
        
        public static string claimConfirm_plan_info {
            get {
                return ResourceManager.GetString("claimConfirm_plan_info", resourceCulture);
            }
        }
        
        public static string claimConfirm_reffered {
            get {
                return ResourceManager.GetString("claimConfirm_reffered", resourceCulture);
            }
        }
        
        public static string claimConfirm_title {
            get {
                return ResourceManager.GetString("claimConfirm_title", resourceCulture);
            }
        }
        
        public static string ClaimSubmissionConfirmationTitle {
            get {
                return ResourceManager.GetString("ClaimSubmissionConfirmationTitle", resourceCulture);
            }
        }
        
        public static string claimConfirm_total {
            get {
                return ResourceManager.GetString("claimConfirm_total", resourceCulture);
            }
        }
        
        public static string claimConfirm_type_expense {
            get {
                return ResourceManager.GetString("claimConfirm_type_expense", resourceCulture);
            }
        }
        
        public static string ClaimDetailsHCSALabel {
            get {
                return ResourceManager.GetString("ClaimDetailsHCSALabel", resourceCulture);
            }
        }
        
        public static string claimResult_button {
            get {
                return ResourceManager.GetString("claimResult_button", resourceCulture);
            }
        }
        
        public static string claimResult_description {
            get {
                return ResourceManager.GetString("claimResult_description", resourceCulture);
            }
        }
        
        public static string claimResult_title {
            get {
                return ResourceManager.GetString("claimResult_title", resourceCulture);
            }
        }
        
        public static string ClaimStatus {
            get {
                return ResourceManager.GetString("ClaimStatus", resourceCulture);
            }
        }
        
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        public static string error_message {
            get {
                return ResourceManager.GetString("error_message", resourceCulture);
            }
        }
        
        public static string HCSAClaimDetailsTitle {
            get {
                return ResourceManager.GetString("HCSAClaimDetailsTitle", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string DisplayByBasedOnServiceDateOfClaim {
            get {
                return ResourceManager.GetString("DisplayByBasedOnServiceDateOfClaim", resourceCulture);
            }
        }
        
        public static string ExplanationOfBenefits {
            get {
                return ResourceManager.GetString("ExplanationOfBenefits", resourceCulture);
            }
        }
        
        public static string InProcess {
            get {
                return ResourceManager.GetString("InProcess", resourceCulture);
            }
        }
        
        public static string ClaimHistorySearch_AllBenefits {
            get {
                return ResourceManager.GetString("ClaimHistorySearch_AllBenefits", resourceCulture);
            }
        }
        
        public static string ClaimHistorySearch_MessageNotFound {
            get {
                return ResourceManager.GetString("ClaimHistorySearch_MessageNotFound", resourceCulture);
            }
        }
        
        public static string ClaimSubmissionResult_HCSATitle {
            get {
                return ResourceManager.GetString("ClaimSubmissionResult_HCSATitle", resourceCulture);
            }
        }
        
        public static string Claim {
            get {
                return ResourceManager.GetString("Claim", resourceCulture);
            }
        }
        
        public static string PlanMemberNoColon {
            get {
                return ResourceManager.GetString("PlanMemberNoColon", resourceCulture);
            }
        }
        
        public static string HealthCareSpendingAccount {
            get {
                return ResourceManager.GetString("HealthCareSpendingAccount", resourceCulture);
            }
        }
        
        public static string ProcessedDate {
            get {
                return ResourceManager.GetString("ProcessedDate", resourceCulture);
            }
        }
        
        public static string PaymentDateNoColon {
            get {
                return ResourceManager.GetString("PaymentDateNoColon", resourceCulture);
            }
        }
        
        public static string AwaitingPaymentNote {
            get {
                return ResourceManager.GetString("AwaitingPaymentNote", resourceCulture);
            }
        }
        
        public static string TotalAmountMustBeGreaterErrorMessage {
            get {
                return ResourceManager.GetString("TotalAmountMustBeGreaterErrorMessage", resourceCulture);
            }
        }
        
        public static string DateOfExpenseTooOld {
            get {
                return ResourceManager.GetString("DateOfExpenseTooOld", resourceCulture);
            }
        }
        
        public static string SubmissionDateLabel {
            get {
                return ResourceManager.GetString("SubmissionDateLabel", resourceCulture);
            }
        }
        
        public static string LineOfBusiness {
            get {
                return ResourceManager.GetString("LineOfBusiness", resourceCulture);
            }
        }
        
        public static string ParticipantWithColon {
            get {
                return ResourceManager.GetString("ParticipantWithColon", resourceCulture);
            }
        }
        
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        public static string DateOfExpenseNoColon {
            get {
                return ResourceManager.GetString("DateOfExpenseNoColon", resourceCulture);
            }
        }
        
        public static string TypeOfExpenseNoColon {
            get {
                return ResourceManager.GetString("TypeOfExpenseNoColon", resourceCulture);
            }
        }
        
        public static string FormNumber {
            get {
                return ResourceManager.GetString("FormNumber", resourceCulture);
            }
        }
        
        public static string CAN {
            get {
                return ResourceManager.GetString("CAN", resourceCulture);
            }
        }
        
        public static string CH {
            get {
                return ResourceManager.GetString("CH", resourceCulture);
            }
        }
        
        public static string EF {
            get {
                return ResourceManager.GetString("EF", resourceCulture);
            }
        }
        
        public static string IncludesTheTotalOfAllClaims {
            get {
                return ResourceManager.GetString("IncludesTheTotalOfAllClaims", resourceCulture);
            }
        }
        
        public static string US {
            get {
                return ResourceManager.GetString("US", resourceCulture);
            }
        }
        
        public static string CashedDateNoColon {
            get {
                return ResourceManager.GetString("CashedDateNoColon", resourceCulture);
            }
        }
        
        public static string ChequeNumberNoColon {
            get {
                return ResourceManager.GetString("ChequeNumberNoColon", resourceCulture);
            }
        }
        
        public static string ChequeStatusNoColon {
            get {
                return ResourceManager.GetString("ChequeStatusNoColon", resourceCulture);
            }
        }
        
        public static string DateOfInquiryNoColon {
            get {
                return ResourceManager.GetString("DateOfInquiryNoColon", resourceCulture);
            }
        }
        
        public static string DepositDateNoColon {
            get {
                return ResourceManager.GetString("DepositDateNoColon", resourceCulture);
            }
        }
        
        public static string DirectDepositNumberNoColon {
            get {
                return ResourceManager.GetString("DirectDepositNumberNoColon", resourceCulture);
            }
        }
        
        public static string PaymentAmountNoColon {
            get {
                return ResourceManager.GetString("PaymentAmountNoColon", resourceCulture);
            }
        }
        
        public static string PaymentCurrencyNoColon {
            get {
                return ResourceManager.GetString("PaymentCurrencyNoColon", resourceCulture);
            }
        }
        
        public static string PaymentMethodNoColon {
            get {
                return ResourceManager.GetString("PaymentMethodNoColon", resourceCulture);
            }
        }
        
        public static string StatementDateNoColon {
            get {
                return ResourceManager.GetString("StatementDateNoColon", resourceCulture);
            }
        }
        
        public static string nameError {
            get {
                return ResourceManager.GetString("nameError", resourceCulture);
            }
        }
        
        public static string nameLengthError {
            get {
                return ResourceManager.GetString("nameLengthError", resourceCulture);
            }
        }
        
        public static string DinFormatError {
            get {
                return ResourceManager.GetString("DinFormatError", resourceCulture);
            }
        }
        
        public static string DINMissingError {
            get {
                return ResourceManager.GetString("DINMissingError", resourceCulture);
            }
        }
        
        public static string FingerprintLoginPrompt {
            get {
                return ResourceManager.GetString("FingerprintLoginPrompt", resourceCulture);
            }
        }
        
        public static string FingerprintConfirmPrompt {
            get {
                return ResourceManager.GetString("FingerprintConfirmPrompt", resourceCulture);
            }
        }
        
        public static string Use {
            get {
                return ResourceManager.GetString("Use", resourceCulture);
            }
        }
        
        public static string DontUse {
            get {
                return ResourceManager.GetString("DontUse", resourceCulture);
            }
        }
        
        public static string ConfirmFingerprintLoginMessage {
            get {
                return ResourceManager.GetString("ConfirmFingerprintLoginMessage", resourceCulture);
            }
        }
        
        public static string ConfirmTouchIDLoginMessage {
            get {
                return ResourceManager.GetString("ConfirmTouchIDLoginMessage", resourceCulture);
            }
        }
        
        public static string ConfirmFaceIDLoginMessage {
            get {
                return ResourceManager.GetString("ConfirmFaceIDLoginMessage", resourceCulture);
            }
        }
        
        public static string GenericErrorDialogTitle {
            get {
                return ResourceManager.GetString("GenericErrorDialogTitle", resourceCulture);
            }
        }
        
        public static string GenericErrorDialogMessage {
            get {
                return ResourceManager.GetString("GenericErrorDialogMessage", resourceCulture);
            }
        }
        
        public static string ServerError_Description {
            get {
                return ResourceManager.GetString("ServerError_Description", resourceCulture);
            }
        }
        
        public static string ServerError_Title {
            get {
                return ResourceManager.GetString("ServerError_Title", resourceCulture);
            }
        }
        
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        public static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        public static string CurrentLocation {
            get {
                return ResourceManager.GetString("CurrentLocation", resourceCulture);
            }
        }
        
        public static string Favourites {
            get {
                return ResourceManager.GetString("Favourites", resourceCulture);
            }
        }
        
        public static string UsingTheHealthProvider {
            get {
                return ResourceManager.GetString("UsingTheHealthProvider", resourceCulture);
            }
        }
        
        public static string ClickHereForDetails {
            get {
                return ResourceManager.GetString("ClickHereForDetails", resourceCulture);
            }
        }
        
        public static string UnderstandingPharmacy {
            get {
                return ResourceManager.GetString("UnderstandingPharmacy", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string ADDFAVOURITIES {
            get {
                return ResourceManager.GetString("ADDFAVOURITIES", resourceCulture);
            }
        }
        
        public static string ADDCONTACT {
            get {
                return ResourceManager.GetString("ADDCONTACT", resourceCulture);
            }
        }
        
        public static string DIRECTIONS {
            get {
                return ResourceManager.GetString("DIRECTIONS", resourceCulture);
            }
        }
        
        public static string GrantPermissionToContacts {
            get {
                return ResourceManager.GetString("GrantPermissionToContacts", resourceCulture);
            }
        }
        
        public static string ProvidersNotFoundWithCurrentCriteria {
            get {
                return ResourceManager.GetString("ProvidersNotFoundWithCurrentCriteria", resourceCulture);
            }
        }
        
        public static string LocationAutocompleteHint {
            get {
                return ResourceManager.GetString("LocationAutocompleteHint", resourceCulture);
            }
        }
        
        public static string AttachmentsExceedsMbLimit {
            get {
                return ResourceManager.GetString("AttachmentsExceedsMbLimit", resourceCulture);
            }
        }
        
        public static string ErrorUploadingFile {
            get {
                return ResourceManager.GetString("ErrorUploadingFile", resourceCulture);
            }
        }
        
        public static string NeedStoragePermission {
            get {
                return ResourceManager.GetString("NeedStoragePermission", resourceCulture);
            }
        }
        
        public static string NeedPhotoLibraryPermission {
            get {
                return ResourceManager.GetString("NeedPhotoLibraryPermission", resourceCulture);
            }
        }
        
        public static string CameraError {
            get {
                return ResourceManager.GetString("CameraError", resourceCulture);
            }
        }
        
        public static string CameraNotAvailable {
            get {
                return ResourceManager.GetString("CameraNotAvailable", resourceCulture);
            }
        }
        
        public static string UploadDocuments {
            get {
                return ResourceManager.GetString("UploadDocuments", resourceCulture);
            }
        }
        
        public static string SelectFiles {
            get {
                return ResourceManager.GetString("SelectFiles", resourceCulture);
            }
        }
        
        public static string SelectPhotos {
            get {
                return ResourceManager.GetString("SelectPhotos", resourceCulture);
            }
        }
        
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        public static string AddAnotherDocument {
            get {
                return ResourceManager.GetString("AddAnotherDocument", resourceCulture);
            }
        }
        
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        public static string BackToMyClaims {
            get {
                return ResourceManager.GetString("BackToMyClaims", resourceCulture);
            }
        }
        
        public static string BackToDashboard {
            get {
                return ResourceManager.GetString("BackToDashboard", resourceCulture);
            }
        }
        
        public static string UploadSuccessful {
            get {
                return ResourceManager.GetString("UploadSuccessful", resourceCulture);
            }
        }
        
        public static string UploadSuccessfulAdditionalMessage {
            get {
                return ResourceManager.GetString("UploadSuccessfulAdditionalMessage", resourceCulture);
            }
        }
        
        public static string ActiveClaimsListLabel {
            get {
                return ResourceManager.GetString("ActiveClaimsListLabel", resourceCulture);
            }
        }
        
        public static string NeedCameraPermission {
            get {
                return ResourceManager.GetString("NeedCameraPermission", resourceCulture);
            }
        }
        
        public static string AddAtLeastOneFile {
            get {
                return ResourceManager.GetString("AddAtLeastOneFile", resourceCulture);
            }
        }
        
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        public static string HaveReadAndAcceptThe {
            get {
                return ResourceManager.GetString("HaveReadAndAcceptThe", resourceCulture);
            }
        }
        
        public static string AcceptDisclaimerFirst {
            get {
                return ResourceManager.GetString("AcceptDisclaimerFirst", resourceCulture);
            }
        }
        
        public static string ClaimHistoryDetailRequriesCopFalse {
            get {
                return ResourceManager.GetString("ClaimHistoryDetailRequriesCopFalse", resourceCulture);
            }
        }
        
        public static string ClaimHistoryDetailRequriesCopTrue {
            get {
                return ResourceManager.GetString("ClaimHistoryDetailRequriesCopTrue", resourceCulture);
            }
        }
        
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        public static string SubmissionConfirmation {
            get {
                return ResourceManager.GetString("SubmissionConfirmation", resourceCulture);
            }
        }
        
        public static string CombinedSizeOfFilesMustBe {
            get {
                return ResourceManager.GetString("CombinedSizeOfFilesMustBe", resourceCulture);
            }
        }
        
        public static string DocumentsToUpload {
            get {
                return ResourceManager.GetString("DocumentsToUpload", resourceCulture);
            }
        }
        
        public static string TwentyFourMb {
            get {
                return ResourceManager.GetString("TwentyFourMb", resourceCulture);
            }
        }
        
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        public static string BottomNavBarClaimsLabel {
            get {
                return ResourceManager.GetString("BottomNavBarClaimsLabel", resourceCulture);
            }
        }
        
        public static string BottomNavBarDashboardLabel {
            get {
                return ResourceManager.GetString("BottomNavBarDashboardLabel", resourceCulture);
            }
        }
        
        public static string BottomNavBarHealthProviderLabel {
            get {
                return ResourceManager.GetString("BottomNavBarHealthProviderLabel", resourceCulture);
            }
        }
        
        public static string BottomNavBarMenuLabel {
            get {
                return ResourceManager.GetString("BottomNavBarMenuLabel", resourceCulture);
            }
        }
        
        public static string DentalRecallExam {
            get {
                return ResourceManager.GetString("DentalRecallExam", resourceCulture);
            }
        }
        
        public static string ChiropracticTreatment {
            get {
                return ResourceManager.GetString("ChiropracticTreatment", resourceCulture);
            }
        }
        
        public static string MassasgeTherapy {
            get {
                return ResourceManager.GetString("MassasgeTherapy", resourceCulture);
            }
        }
        
        public static string DrugsOnTheGo {
            get {
                return ResourceManager.GetString("DrugsOnTheGo", resourceCulture);
            }
        }
        
        public static string RecentClaims {
            get {
                return ResourceManager.GetString("RecentClaims", resourceCulture);
            }
        }
        
        public static string NoRecentClaims {
            get {
                return ResourceManager.GetString("NoRecentClaims", resourceCulture);
            }
        }
        
        public static string CheckCoverage {
            get {
                return ResourceManager.GetString("CheckCoverage", resourceCulture);
            }
        }
        
        public static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        public static string ClaimSummaryTitle {
            get {
                return ResourceManager.GetString("ClaimSummaryTitle", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string ForceUpdateTitle {
            get {
                return ResourceManager.GetString("ForceUpdateTitle", resourceCulture);
            }
        }
        
        public static string UpdateAvailableMessage {
            get {
                return ResourceManager.GetString("UpdateAvailableMessage", resourceCulture);
            }
        }
        
        public static string UpdateAvailableMessage2 {
            get {
                return ResourceManager.GetString("UpdateAvailableMessage2", resourceCulture);
            }
        }
        
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        public static string PasswordChangedErrorTouchId {
            get {
                return ResourceManager.GetString("PasswordChangedErrorTouchId", resourceCulture);
            }
        }
        
        public static string PasswordChangedErrorFaceId {
            get {
                return ResourceManager.GetString("PasswordChangedErrorFaceId", resourceCulture);
            }
        }
        
        public static string PasswordChangedErrorFingerprint {
            get {
                return ResourceManager.GetString("PasswordChangedErrorFingerprint", resourceCulture);
            }
        }
        
        public static string GenericUploadDocuments {
            get {
                return ResourceManager.GetString("GenericUploadDocuments", resourceCulture);
            }
        }
        
        public static string ActionRequiredLabel {
            get {
                return ResourceManager.GetString("ActionRequiredLabel", resourceCulture);
            }
        }
        
        public static string PlanInformation {
            get {
                return ResourceManager.GetString("PlanInformation", resourceCulture);
            }
        }
        
        public static string ClaimCountOutOf {
            get {
                return ResourceManager.GetString("ClaimCountOutOf", resourceCulture);
            }
        }
        
        public static string AuditDetails {
            get {
                return ResourceManager.GetString("AuditDetails", resourceCulture);
            }
        }
        
        public static string AuditDueDateLabel {
            get {
                return ResourceManager.GetString("AuditDueDateLabel", resourceCulture);
            }
        }
        
        public static string AuditInformation {
            get {
                return ResourceManager.GetString("AuditInformation", resourceCulture);
            }
        }
        
        public static string AuditClaimStatus {
            get {
                return ResourceManager.GetString("AuditClaimStatus", resourceCulture);
            }
        }
        
        public static string AuditSummaryPageTitle {
            get {
                return ResourceManager.GetString("AuditSummaryPageTitle", resourceCulture);
            }
        }
        
        public static string AuditListPageTitle {
            get {
                return ResourceManager.GetString("AuditListPageTitle", resourceCulture);
            }
        }
        
        public static string AuditListInstrunction {
            get {
                return ResourceManager.GetString("AuditListInstrunction", resourceCulture);
            }
        }
        
        public static string AuditListImportantNotesLabel {
            get {
                return ResourceManager.GetString("AuditListImportantNotesLabel", resourceCulture);
            }
        }
        
        public static string AuditListNotes {
            get {
                return ResourceManager.GetString("AuditListNotes", resourceCulture);
            }
        }
        
        public static string NoAuditMessage {
            get {
                return ResourceManager.GetString("NoAuditMessage", resourceCulture);
            }
        }
        
        public static string MyBenefits {
            get {
                return ResourceManager.GetString("MyBenefits", resourceCulture);
            }
        }
        
        public static string AgreeAndContinue {
            get {
                return ResourceManager.GetString("AgreeAndContinue", resourceCulture);
            }
        }
        
        public static string SureHealthLink {
            get {
                return ResourceManager.GetString("SureHealthLink", resourceCulture);
            }
        }
        
        public static string ClaimDetailsFor {
            get {
                return ResourceManager.GetString("ClaimDetailsFor", resourceCulture);
            }
        }
        
        public static string PleaseSubmitDocuments {
            get {
                return ResourceManager.GetString("PleaseSubmitDocuments", resourceCulture);
            }
        }
        
        public static string SpecifyDateOfInjury {
            get {
                return ResourceManager.GetString("SpecifyDateOfInjury", resourceCulture);
            }
        }
        
        public static string DateofPrescription12Months {
            get {
                return ResourceManager.GetString("DateofPrescription12Months", resourceCulture);
            }
        }
        
        public static string WorkInjuryCaseNumberError {
            get {
                return ResourceManager.GetString("WorkInjuryCaseNumberError", resourceCulture);
            }
        }
        
        public static string MedicalProfessionalError {
            get {
                return ResourceManager.GetString("MedicalProfessionalError", resourceCulture);
            }
        }
        
        public static string PolicyNo {
            get {
                return ResourceManager.GetString("PolicyNo", resourceCulture);
            }
        }
        
        public static string CertificateNo {
            get {
                return ResourceManager.GetString("CertificateNo", resourceCulture);
            }
        }
        
        public static string SelectParticipantForTreatment {
            get {
                return ResourceManager.GetString("SelectParticipantForTreatment", resourceCulture);
            }
        }
        
        public static string GscIdNumber {
            get {
                return ResourceManager.GetString("GscIdNumber", resourceCulture);
            }
        }
        
        public static string ClaimDetailsOtherBenefitsTitle {
            get {
                return ResourceManager.GetString("ClaimDetailsOtherBenefitsTitle", resourceCulture);
            }
        }
        
        public static string ClaimDetailsOtherBenefitsWithGsc {
            get {
                return ResourceManager.GetString("ClaimDetailsOtherBenefitsWithGsc", resourceCulture);
            }
        }
        
        public static string ClaimDetailsOtherBenefitsSubmitted {
            get {
                return ResourceManager.GetString("ClaimDetailsOtherBenefitsSubmitted", resourceCulture);
            }
        }
        
        public static string ClaimDetailsOtherBenefitsPayBalanceThroughOtherGSC {
            get {
                return ResourceManager.GetString("ClaimDetailsOtherBenefitsPayBalanceThroughOtherGSC", resourceCulture);
            }
        }
        
        public static string ClaimDetailsOtherBenefitsEnterGSC {
            get {
                return ResourceManager.GetString("ClaimDetailsOtherBenefitsEnterGSC", resourceCulture);
            }
        }
        
        public static string ClaimDetailsOtherBenefitsGscNumber {
            get {
                return ResourceManager.GetString("ClaimDetailsOtherBenefitsGscNumber", resourceCulture);
            }
        }
        
        public static string ClaimDetailsOtherBenefitsHSCA {
            get {
                return ResourceManager.GetString("ClaimDetailsOtherBenefitsHSCA", resourceCulture);
            }
        }
        
        public static string ClaimDetailsReasonOfAccident {
            get {
                return ResourceManager.GetString("ClaimDetailsReasonOfAccident", resourceCulture);
            }
        }
        
        public static string ClaimDetailsMotorVehicleTitle {
            get {
                return ResourceManager.GetString("ClaimDetailsMotorVehicleTitle", resourceCulture);
            }
        }
        
        public static string ClaimDetailsMotorVehicleDate {
            get {
                return ResourceManager.GetString("ClaimDetailsMotorVehicleDate", resourceCulture);
            }
        }
        
        public static string ClaimDetailsWorkInjuryTitle {
            get {
                return ResourceManager.GetString("ClaimDetailsWorkInjuryTitle", resourceCulture);
            }
        }
        
        public static string ClaimDetailsWorkInjuryDate {
            get {
                return ResourceManager.GetString("ClaimDetailsWorkInjuryDate", resourceCulture);
            }
        }
        
        public static string ClaimDetailsWorkInjuryCaseNumber {
            get {
                return ResourceManager.GetString("ClaimDetailsWorkInjuryCaseNumber", resourceCulture);
            }
        }
        
        public static string ClaimDetailsOtherTypeOfAccident {
            get {
                return ResourceManager.GetString("ClaimDetailsOtherTypeOfAccident", resourceCulture);
            }
        }
        
        public static string ClaimDetailsMedicalItemTitle {
            get {
                return ResourceManager.GetString("ClaimDetailsMedicalItemTitle", resourceCulture);
            }
        }
        
        public static string ClaimDetailsMedicalItemReferralDate {
            get {
                return ResourceManager.GetString("ClaimDetailsMedicalItemReferralDate", resourceCulture);
            }
        }
        
        public static string ClaimDetailsMedicalItemProfessional {
            get {
                return ResourceManager.GetString("ClaimDetailsMedicalItemProfessional", resourceCulture);
            }
        }
        
        public static string ClaimDetailsTypeOfProfessional {
            get {
                return ResourceManager.GetString("ClaimDetailsTypeOfProfessional", resourceCulture);
            }
        }
        
        public static string ClaimDetailsMedicalItemSport {
            get {
                return ResourceManager.GetString("ClaimDetailsMedicalItemSport", resourceCulture);
            }
        }
        
        public static string ClaimDetailsGstIncludedQ {
            get {
                return ResourceManager.GetString("ClaimDetailsGstIncludedQ", resourceCulture);
            }
        }
        
        public static string ClaimDetailsMassageNoticeText {
            get {
                return ResourceManager.GetString("ClaimDetailsMassageNoticeText", resourceCulture);
            }
        }
        
        public static string InvalidGscNumber {
            get {
                return ResourceManager.GetString("InvalidGscNumber", resourceCulture);
            }
        }
        
        public static string OtherBenefitsGSCNumberError {
            get {
                return ResourceManager.GetString("OtherBenefitsGSCNumberError", resourceCulture);
            }
        }
        
        public static string ClaimDetailsMissingAccidentType {
            get {
                return ResourceManager.GetString("ClaimDetailsMissingAccidentType", resourceCulture);
            }
        }
        
        public static string TreatmentTitle {
            get {
                return ResourceManager.GetString("TreatmentTitle", resourceCulture);
            }
        }
        
        public static string TreatmentDetails {
            get {
                return ResourceManager.GetString("TreatmentDetails", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsTreatmentTitle {
            get {
                return ResourceManager.GetString("TreatmentDetailsTreatmentTitle", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsItemDescription {
            get {
                return ResourceManager.GetString("TreatmentDetailsItemDescription", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsLengthOfTreatment {
            get {
                return ResourceManager.GetString("TreatmentDetailsLengthOfTreatment", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsDateOfTreatment {
            get {
                return ResourceManager.GetString("TreatmentDetailsDateOfTreatment", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsDateOfMonthlyTreatment {
            get {
                return ResourceManager.GetString("TreatmentDetailsDateOfMonthlyTreatment", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsDateOfPurchaseService {
            get {
                return ResourceManager.GetString("TreatmentDetailsDateOfPurchaseService", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsPickUpDate {
            get {
                return ResourceManager.GetString("TreatmentDetailsPickUpDate", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsQuantity {
            get {
                return ResourceManager.GetString("TreatmentDetailsQuantity", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsTotalAmountMedicalItems {
            get {
                return ResourceManager.GetString("TreatmentDetailsTotalAmountMedicalItems", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsTotalAmountOfVisit {
            get {
                return ResourceManager.GetString("TreatmentDetailsTotalAmountOfVisit", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsOrthoMonthlyFee {
            get {
                return ResourceManager.GetString("TreatmentDetailsOrthoMonthlyFee", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsAmountPaidAlt {
            get {
                return ResourceManager.GetString("TreatmentDetailsAmountPaidAlt", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsAmountPaidByPpOrGpIfApplicable {
            get {
                return ResourceManager.GetString("TreatmentDetailsAmountPaidByPpOrGpIfApplicable", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsAmountPaidByPpOrGp {
            get {
                return ResourceManager.GetString("TreatmentDetailsAmountPaidByPpOrGp", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsGstIncluded {
            get {
                return ResourceManager.GetString("TreatmentDetailsGstIncluded", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsPstIncluded {
            get {
                return ResourceManager.GetString("TreatmentDetailsPstIncluded", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsMedicalItem {
            get {
                return ResourceManager.GetString("TreatmentDetailsMedicalItem", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsDateOfReferral {
            get {
                return ResourceManager.GetString("TreatmentDetailsDateOfReferral", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsTypeOfEyewear {
            get {
                return ResourceManager.GetString("TreatmentDetailsTypeOfEyewear", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsTypeOfLens {
            get {
                return ResourceManager.GetString("TreatmentDetailsTypeOfLens", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsFrameAmount {
            get {
                return ResourceManager.GetString("TreatmentDetailsFrameAmount", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsFeeAmount {
            get {
                return ResourceManager.GetString("TreatmentDetailsFeeAmount", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsLensAmount {
            get {
                return ResourceManager.GetString("TreatmentDetailsLensAmount", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsTotalAmountCharged {
            get {
                return ResourceManager.GetString("TreatmentDetailsTotalAmountCharged", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsRightSphere {
            get {
                return ResourceManager.GetString("TreatmentDetailsRightSphere", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsLeftSphere {
            get {
                return ResourceManager.GetString("TreatmentDetailsLeftSphere", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsRightCylinder {
            get {
                return ResourceManager.GetString("TreatmentDetailsRightCylinder", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsLeftCylinder {
            get {
                return ResourceManager.GetString("TreatmentDetailsLeftCylinder", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsRightAxis {
            get {
                return ResourceManager.GetString("TreatmentDetailsRightAxis", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsLeftAxis {
            get {
                return ResourceManager.GetString("TreatmentDetailsLeftAxis", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsRightPrism {
            get {
                return ResourceManager.GetString("TreatmentDetailsRightPrism", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsLeftPrism {
            get {
                return ResourceManager.GetString("TreatmentDetailsLeftPrism", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsRightBifocal {
            get {
                return ResourceManager.GetString("TreatmentDetailsRightBifocal", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsLeftBifocal {
            get {
                return ResourceManager.GetString("TreatmentDetailsLeftBifocal", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsProcedureCode {
            get {
                return ResourceManager.GetString("TreatmentDetailsProcedureCode", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsToothCode {
            get {
                return ResourceManager.GetString("TreatmentDetailsToothCode", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsToothSurface {
            get {
                return ResourceManager.GetString("TreatmentDetailsToothSurface", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsDentistFee {
            get {
                return ResourceManager.GetString("TreatmentDetailsDentistFee", resourceCulture);
            }
        }
        
        public static string TreatmentDetailsLabCharge {
            get {
                return ResourceManager.GetString("TreatmentDetailsLabCharge", resourceCulture);
            }
        }
        
        public static string DeleteTreatmentDetail {
            get {
                return ResourceManager.GetString("DeleteTreatmentDetail", resourceCulture);
            }
        }
        
        public static string InvalidTreatmentDate24MonthValidation {
            get {
                return ResourceManager.GetString("InvalidTreatmentDate24MonthValidation", resourceCulture);
            }
        }
        
        public static string MissingProcedureCodeValidation {
            get {
                return ResourceManager.GetString("MissingProcedureCodeValidation", resourceCulture);
            }
        }
        
        public static string InvalidProcedureCodeValidation {
            get {
                return ResourceManager.GetString("InvalidProcedureCodeValidation", resourceCulture);
            }
        }
        
        public static string MissingToothCodeValidation {
            get {
                return ResourceManager.GetString("MissingToothCodeValidation", resourceCulture);
            }
        }
        
        public static string InvalidToothCodeValidation {
            get {
                return ResourceManager.GetString("InvalidToothCodeValidation", resourceCulture);
            }
        }
        
        public static string MissingToothSurfaceValidation {
            get {
                return ResourceManager.GetString("MissingToothSurfaceValidation", resourceCulture);
            }
        }
        
        public static string InvalidToothSurfaceValidation {
            get {
                return ResourceManager.GetString("InvalidToothSurfaceValidation", resourceCulture);
            }
        }
        
        public static string MissingDentistFeeValidation {
            get {
                return ResourceManager.GetString("MissingDentistFeeValidation", resourceCulture);
            }
        }
        
        public static string InvalidDentistFeeValidation {
            get {
                return ResourceManager.GetString("InvalidDentistFeeValidation", resourceCulture);
            }
        }
        
        public static string MissingLaboratoryChargeValidation {
            get {
                return ResourceManager.GetString("MissingLaboratoryChargeValidation", resourceCulture);
            }
        }
        
        public static string InvalidLaboratoryChargeValidation {
            get {
                return ResourceManager.GetString("InvalidLaboratoryChargeValidation", resourceCulture);
            }
        }
        
        public static string MissingDentistFeeOrLaboratoryChargeValidation {
            get {
                return ResourceManager.GetString("MissingDentistFeeOrLaboratoryChargeValidation", resourceCulture);
            }
        }
        
        public static string MissingAmountPaidValidation {
            get {
                return ResourceManager.GetString("MissingAmountPaidValidation", resourceCulture);
            }
        }
        
        public static string InvalidAmountPaidValidation {
            get {
                return ResourceManager.GetString("InvalidAmountPaidValidation", resourceCulture);
            }
        }
        
        public static string MissingAmountPaidByPpOrGpValidation {
            get {
                return ResourceManager.GetString("MissingAmountPaidByPpOrGpValidation", resourceCulture);
            }
        }
        
        public static string InvalidAmountPaidByPpOrGpValidation {
            get {
                return ResourceManager.GetString("InvalidAmountPaidByPpOrGpValidation", resourceCulture);
            }
        }
        
        public static string ClaimSubmissionFootNotes {
            get {
                return ResourceManager.GetString("ClaimSubmissionFootNotes", resourceCulture);
            }
        }
        
        public static string UploadedClaim {
            get {
                return ResourceManager.GetString("UploadedClaim", resourceCulture);
            }
        }
        
        public static string ProviderEntryAllMissing {
            get {
                return ResourceManager.GetString("ProviderEntryAllMissing", resourceCulture);
            }
        }
        
        public static string ProviderEntryNameInvalid {
            get {
                return ResourceManager.GetString("ProviderEntryNameInvalid", resourceCulture);
            }
        }
        
        public static string ProviderEntryAddressInvalid {
            get {
                return ResourceManager.GetString("ProviderEntryAddressInvalid", resourceCulture);
            }
        }
        
        public static string ProviderEntryCityInvalid {
            get {
                return ResourceManager.GetString("ProviderEntryCityInvalid", resourceCulture);
            }
        }
        
        public static string ProviderEntryPostalCodeInvalid {
            get {
                return ResourceManager.GetString("ProviderEntryPostalCodeInvalid", resourceCulture);
            }
        }
        
        public static string ProviderEntryPhoneInvalid {
            get {
                return ResourceManager.GetString("ProviderEntryPhoneInvalid", resourceCulture);
            }
        }
        
        public static string ProviderEntryRegistrationNumberInvalid {
            get {
                return ResourceManager.GetString("ProviderEntryRegistrationNumberInvalid", resourceCulture);
            }
        }
        
        public static string ProviderEntryTitle {
            get {
                return ResourceManager.GetString("ProviderEntryTitle", resourceCulture);
            }
        }
        
        public static string ProviderEntryEnterDetails {
            get {
                return ResourceManager.GetString("ProviderEntryEnterDetails", resourceCulture);
            }
        }
        
        public static string ProviderEntryMandatoryFields {
            get {
                return ResourceManager.GetString("ProviderEntryMandatoryFields", resourceCulture);
            }
        }
        
        public static string ProviderEntryName {
            get {
                return ResourceManager.GetString("ProviderEntryName", resourceCulture);
            }
        }
        
        public static string ProviderEntryAddress1 {
            get {
                return ResourceManager.GetString("ProviderEntryAddress1", resourceCulture);
            }
        }
        
        public static string ProviderEntryAddress2 {
            get {
                return ResourceManager.GetString("ProviderEntryAddress2", resourceCulture);
            }
        }
        
        public static string ProviderEntryCity {
            get {
                return ResourceManager.GetString("ProviderEntryCity", resourceCulture);
            }
        }
        
        public static string ProviderEntryProvince {
            get {
                return ResourceManager.GetString("ProviderEntryProvince", resourceCulture);
            }
        }
        
        public static string ProviderEntryPostalCode {
            get {
                return ResourceManager.GetString("ProviderEntryPostalCode", resourceCulture);
            }
        }
        
        public static string ProviderEntryPostalCodeAndroid {
            get {
                return ResourceManager.GetString("ProviderEntryPostalCodeAndroid", resourceCulture);
            }
        }
        
        public static string ProviderEntryPhone {
            get {
                return ResourceManager.GetString("ProviderEntryPhone", resourceCulture);
            }
        }
        
        public static string ProviderEntryRegistration {
            get {
                return ResourceManager.GetString("ProviderEntryRegistration", resourceCulture);
            }
        }
        
        public static string ProviderEntryButtonText {
            get {
                return ResourceManager.GetString("ProviderEntryButtonText", resourceCulture);
            }
        }
        
        public static string DeductibleAmount {
            get {
                return ResourceManager.GetString("DeductibleAmount", resourceCulture);
            }
        }
        
        public static string CopayAmount {
            get {
                return ResourceManager.GetString("CopayAmount", resourceCulture);
            }
        }
        
        public static string PlanLimitationParticipantType {
            get {
                return ResourceManager.GetString("PlanLimitationParticipantType", resourceCulture);
            }
        }
        
        public static string PlanLimitationAmountUsedToDate {
            get {
                return ResourceManager.GetString("PlanLimitationAmountUsedToDate", resourceCulture);
            }
        }
        
        public static string PlanLimitationOccurrencesToDate {
            get {
                return ResourceManager.GetString("PlanLimitationOccurrencesToDate", resourceCulture);
            }
        }
        
        public static string PlanLimitations {
            get {
                return ResourceManager.GetString("PlanLimitations", resourceCulture);
            }
        }
        
        public static string GenericAwaitingPaymentNote {
            get {
                return ResourceManager.GetString("GenericAwaitingPaymentNote", resourceCulture);
            }
        }
        
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        public static string ClaimPlanParticipants {
            get {
                return ResourceManager.GetString("ClaimPlanParticipants", resourceCulture);
            }
        }
        
        public static string SessionTimedOutMessage {
            get {
                return ResourceManager.GetString("SessionTimedOutMessage", resourceCulture);
            }
        }
        
        public static string DirectDeposit {
            get {
                return ResourceManager.GetString("DirectDeposit", resourceCulture);
            }
        }
        
        public static string DirectDepositNavbarSubtitle1 {
            get {
                return ResourceManager.GetString("DirectDepositNavbarSubtitle1", resourceCulture);
            }
        }
        
        public static string DirectDepositNavbarSubtitle2 {
            get {
                return ResourceManager.GetString("DirectDepositNavbarSubtitle2", resourceCulture);
            }
        }
        
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        public static string DirectDepositOptOutMessage {
            get {
                return ResourceManager.GetString("DirectDepositOptOutMessage", resourceCulture);
            }
        }
        
        public static string DirectDepositBankingInfoTitle {
            get {
                return ResourceManager.GetString("DirectDepositBankingInfoTitle", resourceCulture);
            }
        }
        
        public static string DirectDepositBankingInfoMessage {
            get {
                return ResourceManager.GetString("DirectDepositBankingInfoMessage", resourceCulture);
            }
        }
        
        public static string DirectDepositTransitNumber {
            get {
                return ResourceManager.GetString("DirectDepositTransitNumber", resourceCulture);
            }
        }
        
        public static string DirectDepositBankNumber {
            get {
                return ResourceManager.GetString("DirectDepositBankNumber", resourceCulture);
            }
        }
        
        public static string DirectDepositAccountNumber {
            get {
                return ResourceManager.GetString("DirectDepositAccountNumber", resourceCulture);
            }
        }
        
        public static string SaveAndContinue {
            get {
                return ResourceManager.GetString("SaveAndContinue", resourceCulture);
            }
        }
        
        public static string DirectDepositEmailPreferencesTitle {
            get {
                return ResourceManager.GetString("DirectDepositEmailPreferencesTitle", resourceCulture);
            }
        }
        
        public static string DirectDepositReceiveEmailNotification {
            get {
                return ResourceManager.GetString("DirectDepositReceiveEmailNotification", resourceCulture);
            }
        }
        
        public static string DirectDepositDoNotReceiveEmailNotification {
            get {
                return ResourceManager.GetString("DirectDepositDoNotReceiveEmailNotification", resourceCulture);
            }
        }
        
        public static string DirectDepositFinePrints {
            get {
                return ResourceManager.GetString("DirectDepositFinePrints", resourceCulture);
            }
        }
        
        public static string DirectDepositDisclaimer1 {
            get {
                return ResourceManager.GetString("DirectDepositDisclaimer1", resourceCulture);
            }
        }
        
        public static string DirectDepositDisclaimer2 {
            get {
                return ResourceManager.GetString("DirectDepositDisclaimer2", resourceCulture);
            }
        }
        
        public static string DirectDepositDisclaimer3 {
            get {
                return ResourceManager.GetString("DirectDepositDisclaimer3", resourceCulture);
            }
        }
        
        public static string DirectDepositDisclaimer3B {
            get {
                return ResourceManager.GetString("DirectDepositDisclaimer3B", resourceCulture);
            }
        }
        
        public static string EligibilityResultsPCAndPGText {
            get {
                return ResourceManager.GetString("EligibilityResultsPCAndPGText", resourceCulture);
            }
        }
        
        public static string InvalidBankNumberValidation {
            get {
                return ResourceManager.GetString("InvalidBankNumberValidation", resourceCulture);
            }
        }
        
        public static string InvalidAccountNumberValidation {
            get {
                return ResourceManager.GetString("InvalidAccountNumberValidation", resourceCulture);
            }
        }
        
        public static string InvalidTransitNumberValidation {
            get {
                return ResourceManager.GetString("InvalidTransitNumberValidation", resourceCulture);
            }
        }
        
        public static string DDValidationErrWarning {
            get {
                return ResourceManager.GetString("DDValidationErrWarning", resourceCulture);
            }
        }
        
        public static string DDValidationError {
            get {
                return ResourceManager.GetString("DDValidationError", resourceCulture);
            }
        }
        
        public static string DDValidationErrorPart1 {
            get {
                return ResourceManager.GetString("DDValidationErrorPart1", resourceCulture);
            }
        }
        
        public static string DDValidationErrorPart2 {
            get {
                return ResourceManager.GetString("DDValidationErrorPart2", resourceCulture);
            }
        }
        
        public static string DDValidationErrorPart3 {
            get {
                return ResourceManager.GetString("DDValidationErrorPart3", resourceCulture);
            }
        }
        
        public static string DDValidationErrorPart4 {
            get {
                return ResourceManager.GetString("DDValidationErrorPart4", resourceCulture);
            }
        }
        
        public static string DDValidationErrorPart5 {
            get {
                return ResourceManager.GetString("DDValidationErrorPart5", resourceCulture);
            }
        }
        
        public static string DDValidationErrNote {
            get {
                return ResourceManager.GetString("DDValidationErrNote", resourceCulture);
            }
        }
        
        public static string DDValidationErrNoteContact {
            get {
                return ResourceManager.GetString("DDValidationErrNoteContact", resourceCulture);
            }
        }
        
        public static string DDValidationErrNoteContinue {
            get {
                return ResourceManager.GetString("DDValidationErrNoteContinue", resourceCulture);
            }
        }
        
        public static string DDValidationErrExplaination {
            get {
                return ResourceManager.GetString("DDValidationErrExplaination", resourceCulture);
            }
        }
        
        public static string DDValidationErrBankInfo {
            get {
                return ResourceManager.GetString("DDValidationErrBankInfo", resourceCulture);
            }
        }
        
        public static string ChangeInformationTitle {
            get {
                return ResourceManager.GetString("ChangeInformationTitle", resourceCulture);
            }
        }
        
        public static string DDConfirmUpdateLabel {
            get {
                return ResourceManager.GetString("DDConfirmUpdateLabel", resourceCulture);
            }
        }
        
        public static string DDConfirmNoteConfirmationLabel {
            get {
                return ResourceManager.GetString("DDConfirmNoteConfirmationLabel", resourceCulture);
            }
        }
        
        public static string DDClickLabel {
            get {
                return ResourceManager.GetString("DDClickLabel", resourceCulture);
            }
        }
        
        public static string DDNoteConfirmation {
            get {
                return ResourceManager.GetString("DDNoteConfirmation", resourceCulture);
            }
        }
        
        public static string DDChangeInformationLabel {
            get {
                return ResourceManager.GetString("DDChangeInformationLabel", resourceCulture);
            }
        }
        
        public static string DDResultSuccessSubTitle {
            get {
                return ResourceManager.GetString("DDResultSuccessSubTitle", resourceCulture);
            }
        }
        
        public static string DDResultDisclaimer1 {
            get {
                return ResourceManager.GetString("DDResultDisclaimer1", resourceCulture);
            }
        }
        
        public static string DDResultDisclaimer2 {
            get {
                return ResourceManager.GetString("DDResultDisclaimer2", resourceCulture);
            }
        }
        
        public static string DirectDepositSuccess {
            get {
                return ResourceManager.GetString("DirectDepositSuccess", resourceCulture);
            }
        }
        
        public static string AppReviewBody {
            get {
                return ResourceManager.GetString("AppReviewBody", resourceCulture);
            }
        }
        
        public static string BenefitsDisclaimer1 {
            get {
                return ResourceManager.GetString("BenefitsDisclaimer1", resourceCulture);
            }
        }
        
        public static string BenefitsDisclaimer2 {
            get {
                return ResourceManager.GetString("BenefitsDisclaimer2", resourceCulture);
            }
        }
    }
}
